### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by malvikarao** [bugmark/bugmark_docs#33]
What is a blockchain? How are blockchains used?

**Comment by snehasi** [comment]
Blockchain is a _digital, decentralised, distributed ledger_. 
Blockchain is made of data structured by rules, and relying on the fact that this data cannot be modified or copied, theoretically. Data keeps growing continuously, in blocks which are linked and have a timestamp. Each block has a hash, a set of characters sort of, like an encrypted code word. 
There is no central authority to maintain or validate the ledger record- it's distributed publicly over a network of computers.
Transactions are made in Blockchain using cryptocurrencies.

Some uses of Blockchain I found especially interesting are:

- Digital Assets - like ICO, investment can be raised through tokens which are stored on Blockc

**Comment by malvikarao** [comment]
Hi Sneha,

Thank you for your comments. The issues in bugmark/docs are being created for a live experiment we will be running in a couple of weeks. We will continue to create more issues for this purpose. If you would like to participate in this experiment let us know. In the meantime feel free to contribute more issues (not answers) that we can add to our collection for the experiment.

Thanks,
Malvika

**Comment by snehasi** [comment]
Hey Malvika,

Sorry, I thought this was a genuine question for a short intro to Blockchain!
I would love to participate in this experiment. I'll look at some issues I can open, in the meantime.

Thanks,
Sneha

**Comment by malvikarao** [comment]
Great. Can you just suggest/email me any issues first? We need to be careful about what issues make it into this repo to have a well-designed experiment. Thanks.

**Comment by snehasi** [comment]
Sure, I will do that.
